spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/auth/**, /api/admin/**

        - id: ticket-service-route
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**

server:
  port: 8090

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: ticket-service
        url: /ticket-service/v3/api-docs
  api-docs:
    enabled: true