services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-user
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-config.json
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${POSTGRESQL_DATABASE}
      KC_DB_USERNAME: ${POSTGRESQL_USERNAME}
      KC_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ../realm-config.json:/opt/keycloak/data/import/realm-config.json
    command: ["start-dev", "--import-realm"]
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db-user
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "5432:5432"