spring:
  application:
    name: user-service

server:
  port: 1111

keycloak:
  admin:
    clientId: admin-cli
    clientSecret: cwixIcZRsdsqD5Rir8skSqo1bRDrzTDH
  realm: support-application-user
  serverUrl: http://localhost:8080
