spring:
  application:
    name: user-service
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}

server:
  port: 1111

keycloak:
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
  admin:
    id: ${ADMIN_ID}
    secret: ${ADMIN_SECRET}
  realm: ${REALM_NAME}
  serverUrl: ${SERVER_URL}
