server:
  port: 8082

user:
  service:
    url: http://localhost:8080

spring:
  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/${MONGO_DATABASE}?authSource=admin

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG